### ISSUE TITLE
front end in get books 

### ISSUE THREAD

**Issue by ghudson46** [jhf1203/Project-2#38]
use the getbookinfo method to populate the book table, then pull from the book table into the front end

**Comment by jhf1203** [comment]
Had a thought overnight...if the xml file from goodreads gives you trouble we could scale back to just use the google books API.  We switched to goodreads to provide ratings only, but if we highlight our internal user ratings only then the goodreads wouldn't be needed.  This would also make the routes and calls a lot more straightforward.
